@startuml
class Sonic
class Personaje
class Villano
class Ataque
class Recolector
class AnilloDorado
class AnilloRojo
class AnilloDeEstrella
class VidaExtra
class Invencibilidad
class EscudoNormal
class EscudoElemental 
class Velocidad
class SuperPoder
class EsmeraldaDelCaos
class Plataforma
class Resorte
Class Juego
class PlataformaMovil
class ObjetoEspecial
class LlaveEspecial
class LlaveDeNivel
class Habilidad
Personaje  <|-- Villano
Personaje  <|--  Sonic
Plataforma "1" <|-- "*" PlataformaMovil 
Plataforma "1" <|-- "*" Resorte
Sonic "1" o-- "*" Plataforma
Sonic "1" o-- "*" Recolector 
Recolector "1" -- "*" Anillo
Anillo "*" <|-- "*" AnilloRojo
Anillo "*" <|-- "*" AnilloDorado
Anillo "*" <|-- "*" AnilloDeEstrella
Habilidad "1" <|-- "1" Invencibilidad 
Habilidad "1" <|-- "1" VidaExtra
Habilidad "1" <|-- "1" SuperPoder
ObjetoEspecial "1" <|-- "*" LlaveDeNivel
ObjetoEspecial "1" <|-- "*" LlaveEspecial
Sonic "1" o-- "*" ObjetoEspecial
Habilidad "1" <|-- "*" Velocidad
Habilidad "1" <|-- "*" Ataque
Habilidad "1" <|-- "*" EscudoNormal
Habilidad "1"<|-- "1" EsmeraldaDelCaos
Habilidad "1" <|-- "1" EscudoElemental
Sonic "1" o-- "*" Habilidad
Villano "1" o-- "*" Plataforma
Juego  *--  Personaje
@enduml